- id: doi:10.1182/bloodadvances.2023010535
  type: paper
  description: >
    Biochemical and metabolic profiling integrated with current AML risk classifiers
    identifies distinct molecular subtypes with differential drug sensitivities.
  date: 2024-03-01
  image: https://ashpublications.org/view-large/figure/12166862/BLOODA_ADV-2023-010535-gr2.jpg
  buttons:
    - type: paper
  tags:
    - AML
    - metabolism
    - risk classification
