- id: doi:10.1182/bloodadvances.2023010535
  type: paper
  description: >
    Biochemical and metabolic profiling integrated with current AML risk classifiers
    identifies distinct molecular subtypes with differential drug sensitivities.
  date: 2024-03-01
  image: images/bloodadv.jpg
  buttons:
    - type: paper
  tags:
    - AML
    - metabolism
    - risk classification
  
- id: doi:10.1038/s41467-023-37914-x
  type: paper
  description: >
    Oncogeneic receptor activation reconfigures nucleocytoplasmic transport leading to mislocalization of key regulators and early onset of tumorigenesis in breast epithelia.
  date: 2023-04-13
  image: images/natcom.jpg
  buttons:
    - type: paper
  tags:
    - Breast cancer
    - systems biology
    - nucleocytoplasmic transport
    - tumorigenesis

- id: doi:10.1016/j.jbc.2025.111062
  type: paper
  description: >
    We developed an automated image analytical pipeline to process replicative budding events from Microfluidic microscopic images. The pipeline Microfluidic (Micro) Budding Replicative Events Workflow (BREW)--MicroBREW automatically detects and process high-throughput images and results in easy-to-summarize results.
  buttons: 
    -type: paper 
  tags: 
    - tool 
    - yeast 
    - pipeline
