- id: doi:10.1182/bloodadvances.2023010535
  type: paper
  description: >
    Biochemical and metabolic profiling integrated with current AML risk classifiers
    identifies distinct molecular subtypes with differential drug sensitivities.
  date: 2024-03-01
  image: https://ashpublications.org/view-large/figure/12166862/BLOODA_ADV-2023-010535-gr2.jpg
  buttons:
    - type: manubot
  tags:
    - AML
    - metabolism
    - risk classification

- id: doi:10.1038/s41467-023-37914-x
  type: paper
  image: https://www.nature.com/articles/s41467-023-37914-x/figures/7
  buttons:
    - type: doi
      link: https://doi.org/10.1038/s41467-023-37914-x
  tags:
    - systems biology
    - metabolism
